services:
  back-api:
    container_name: barilo-back-api
    build: .
    image: barilo-back-api
    ports:
      - 8443:8443
    environment:
      DATASOURCE_PROD: ${DATASOURCE_PROD}
      USER_PROD: ${USER_PROD}
      PASSWORD_PROD: ${PASSWORD_PROD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JPA_HIBERNATE_DDL_AUTO: ${JPA_HIBERNATE_DDL_AUTO}
    restart: always